# Stage 1: Build the Go binary
FROM registry.access.redhat.com/ubi9/go-toolset:latest as builder

WORKDIR /app

# Initialize Go module and download dependencies
RUN go mod init serve-it && \
    go mod tidy

# Copy the source code into the container
COPY serve-it.go .

# Build the Go binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

# Stage 2: Create a lightweight image with the Go binary
FROM registry.access.redhat.com/ubi9/ubi-micro:latest

# Copy the Go binary from the builder stage
COPY --from=builder /app/server .

# Expose port 8080
EXPOSE 8080

# Run the server binary
CMD ["./server"]
